### ISSUE TITLE
Add an option to set title manually

### ISSUE THREAD

**Issue by elai950** [rebeloper/WKView#2]
In my app, I'm trying to display the terms and conditions and for some reason, the title still shows Loading...
I would like to have an option for setting the title manually so I could use this dependency with a website that doesn't auto receiving the title from it.

Currently:
Even if I'm using "https://rebeloper.com" it still shows me Loading...

**Comment by rebeloper** [comment]
This is a great feature! Have added `title`:

`WebView(url: "https://rebeloper.com", title: "WKView")`

This will be a constant title used -**_instead_**- of the web page's title.
