### ISSUE TITLE
Archiving Build Error

### ISSUE THREAD

**Issue by unobrandon** [rebeloper/WKView#3]
This is a weird error in Xcode where if you Archive your latest build it can not recognize the SwiftUI code.
The solution is to add the platform version to the Package Description (Package.swift) file shown below:

`    platforms: [
        .iOS(.v14)
    ],
`

![Screen Shot 2020-12-22 at 12 51 42 PM](https://user-images.githubusercontent.com/8461210/102918205-7ec95f00-4454-11eb-97b7-e349d3b81328.png)

**Comment by rebeloper** [comment]
Thanks for this 👍 Have adde to 0.1.6: https://github.com/rebeloper/WKView/releases/tag/0.1.6
